### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [chromaui/learnstorybook-code#55]
It has been noticed that while using chromaui/action@v1 your projectToken injbe7ej2u is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by jonniebigodes** [comment]
@raima-zachariah thank you for bringing this to our attention. I'm currently maintaining this repo and I left this intentionally when updating the codebase so that users could see the workflow working properly. I understand your concern but don't worry, the token is tied to an app registered under my user account, so each build that is triggered by for instance you or any other user that forks the repo will generate an alert and I can check the changes and block/deny them. 

As I've been working on this repo and its sibling (the tutorial one) I have a good understanding of the shape of the stories and what should be available in Chromatic.

Stay safe

**Comment by jonniebigodes** [comment]
Closing this issue as answered
