### ISSUE TITLE
Missing components for React Native tutorial

### ISSUE THREAD

**Issue by Konntroll** [chromaui/learnstorybook-code#60]
Hi!

It may be me, but it looks like the tutorial for React Native is missing a couple of things, namely:

```
import TabBarIcon from '../components/TabBarIcon';
import HomeScreen from '../screens/HomeScreen';
```

Couldn't find those anywhere and would appreciate it if you could point me in the right direction.

Nunito fonts are also not included in the folder linked in the tutorial, though these can be downloaded from Google.

I'm assuming this could be because the tutorial is a translation of an older guide?

**Comment by jonniebigodes** [comment]
@Konntroll the tutorial for React Native has been on a holding pattern for quite some time and it's due a bit of an overall. Mostly because I was hoping for Storybook for React Native to be updated to use controls and other features that are currently mainstream for other versions. With this out of the way. The fonts should be accessible no problem, but I'll check it out in another machine as the one I'm typing this answer doesn't have svn installed.

Regarding this:
> It may be me, but it looks like the tutorial for React Native is missing a couple of things, namely:

Those components you've mentioned are part of the expo template used in the tutorial. Or at least they were at the time of writing the tutorial. 

Like I said above, that version of the tutorial requires a bit of polish. I'll continue to coordinate with the maintainer of Storybook for React Native and get an estimate on when Storybook for React Native moves from the alpha version to stable in order to update the tutorial, and implement the same approach used with the other versions of the tutorial. More specifically a boilerplate template that you or any other reader can easily download and go through the tutorial without having to at the lack of a better adjective, jump through hoops to get started with Storybook and React Native.

Stay safe

**Comment by Konntroll** [comment]
@jonniebigodes, thanks for the detailed answer. Much appreciated.

I knew I missed something! In this case, Expo. Oh, well. It will be good to see a more up-to-date guide when it lands.

All the best

**Comment by jonniebigodes** [comment]
@Konntroll no need to thank, glad that I was able to provide some context on the issue. Indeed this will require some work but hopefully, it will get updated sometime soon. 

Stay safe
