### ISSUE TITLE
Problems used in typescript

### ISSUE THREAD

**Issue by DanaCoding** [chromaui/learnstorybook-code#66]
I have a question. When using `interface` in a component, the data type can be defined very well. In my practice, it really performs well in the storybook. but! , When I switch to the app itself, I even only see a blank page. How can I make the component itself be able to use this type to render in the browser?
Should I comment it out? Assign value again?

>Short example component.tsx

```base
interface props {
  value: string
}
export default function({value}:props){
   retutn(
      <div>{value}<div>
   )
}
```

**Comment by jonniebigodes** [comment]
@DanaCoding can you elaborate a bit on this issue and provide some more detailed examples so that we can follow up with you on this?

Have a great day.

Stay safe

**Comment by DanaCoding** [comment]
I think I have figured out the problem clearly, that is, using the CDD development model, and finally rendering the data only at the page level.

**Comment by jonniebigodes** [comment]
@DanaCoding let me know how it turned out and should you face any issues let me know and we can re-open the issue, or join our [Discord server](https://discord.gg/UUt2PJb) and post the question there, our community is really helpful and will probably be able to give you some guidance.


Have a great weekend!


Stay safe
