### ISSUE TITLE
Interactions in Vue example not working correctly

### ISSUE THREAD

**Issue by Voodu** [chromaui/learnstorybook-code#83]
I was following the Vue tutorial and stumbled upon a small issue with the interactions - they don't really do anything.

As I've managed to figure out, it's the mocked Vuex store - its actions don't update the state:
https://github.com/chromaui/learnstorybook-code/blob/c58dc1c34c036445e0a9c4a7d6e5edd0f5770d97/src/components/PureInboxScreen.stories.js#L25-L31

I've managed to fix this by simply using the same code as in the normal store, i.e.:
```javascript
actions: {
    archiveTask({ commit }, id) {
      commit('ARCHIVE_TASK', id);
    },
    pinTask({ commit }, id) {
      commit('PIN_TASK', id);
    },
},
```

However, now `With Interactions` story affects other stories, so they are not really isolated correctly.
I'm just starting learning Storybook, though, so I couldn't come up with a better way to fix that.

**Comment by jonniebigodes** [comment]
@Voodu thanks for reaching out to us with your issue and raising that perfectly valid question. This is something that we're aware of and hopefully, we'll be able to provide a better way to address it. I've been personally looking into some alternatives to see if they would fit in the context of the tutorial and that's still a work in progress. If any of them work and provide the same experience as documented in the other versions of the tutorial, I'm more than glad to make the pull request and adjust the tutorial so that not only you but the rest of the community can also benefit from it. 


Hope I was able to provide you with a bit of context.

Stay safe
