### ISSUE TITLE
which is the react native branch?

### ISSUE THREAD

**Issue by dgamma3** [chromaui/learnstorybook-code#92]
following this tutorial:

https://storybook.js.org/tutorials/intro-to-storybook/react-native/en/get-started/

which is the react-native branch?

**Comment by jonniebigodes** [comment]
Thanks for reaching out to us with your question, and sorry for the delayed response, but it's been a busy season here at Storybook. So that you and everyone else who checks this issue, I and the rest of the maintainers decided against having a dedicated branch containing the code as there's a parity gap between the React Native version and the other versions (e.g., React, Angular). Until that gap is mitigated, we'll not commit to it and keep it out of the code repository. Sorry for the inconvenience and hope you don't take it the wrong way, but going to close it for now.

Hope you have a fantastic holiday season

Stay safe
